name: pipeline

on:
  workflow_dispatch:

jobs:
  estagio01:
    runs-on: ubuntu-latest
    steps:
      - name: Olá, mundo
        run: echo "Olá, mundo eu sou o pipeline!"

  estagio02:
    name: sleep1
    needs: estagio01
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 5
        run: sleep 5

  estagio03:
    name: sleep2
    needs: estagio02
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 5
        run: sleep 5